config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (
    HomePageView, RegisterView, LoginView, 
    CourseDetailView, AddCourseView, UpdateCourseView,
    NewsListView, NewsDetailView
)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('register', RegisterView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="kirish"),
    path('course/<str:slug>', CourseDetailView.as_view(), name="detail"),
    path('add_course', AddCourseView.as_view(), name="add_course"),
    path('course/<int:pk>/edit', UpdateCourseView.as_view(), name="update_course"),
    path('news/', NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
]

templates/course_add.html
{% extends 'page_wrapper.html' %}
{% block page %}
	<!-- inner header wrapper start -->
	<div class="page_title_section float_left">
		<div class="page_header">
			<div class="container">
				<div class="row">
					<!-- section_heading start -->
					<div class="col-lg-12 col-md-12 col-12 col-sm-12">
						<h1>Course single</h1>
					</div>
					<div class="col-lg-12 col-md-12 col-12 col-sm-12">
						<div class="sub_title_section">
							<ul class="sub_title">
								<li> <a href="#"> Home </a> &nbsp;&nbsp;&nbsp; &gt; &nbsp;&nbsp;</li>
								<li>Course single</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- inner header wrapper end -->
	<!--blog wrapper start-->
	<div class="blog_wrapper float_left">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">

                    <form action="" method="post" enctype="multipart/form-data">
                       {% csrf_token %}

                     {% if form.errors %}  
                        {% for error in  form.errors %}
                            <h1>{{ error }}</h1>
                        {% endfor %}  
                     {% endif %}  

                       
                     {% for field in form %}
                        <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                        </div>
                     {% endfor %} 
                     
                     <div class="form-group">
                        <button class="btn btn-success" type="submit"> {{ button }} </button>
                     </div>

                       
                    </form>

               </div>     
            </div>     
        </div>     
    </div>     
{% endblock page %}

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Header</title>
</head>
<body>
    <h1>Header</h1>
    {% for header in headers %}
        <div>
            <h2>{{ header.message }}</h2>
            <p>Facebook: {{ header.facebook }}</p>
            <p>Twitter: {{ header.twitter }}</p>
            <p>Youtube: {{ header.youtube }}</p>
            <p>LinkedIn: {{ header.linkedin }}</p>
            <img src="{{ header.logo.url }}" alt="Logo">
            <p>Address: {{ header.address }}</p>
            <p>Phone1: {{ header.phone1 }}</p>
            <p>Phone2: {{ header.phone2 }}</p>
            <p>Email1: {{ header.email1 }}</p>
            <p>Email2: {{ header.email2 }}</p>
        </div>
    {% endfor %}
    <h1>Header Images</h1>
    {% for header_image in header_images %}
        <div>
            <h2>{{ header_image.service }}</h2>
            <p>{{ header_image.content }}</p>
            <img src="{{ header_image.image.url }}" alt="Service Image">
        </div>
    {% endfor %}
</body>
</html>

templates/news_detail.html
{% extends 'base.html' %}
    {% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ news.title }}</title>
</head>
<body>
    <h1>{{ news.title }}</h1>
    <p>{{ news.content }}</p>
    <h2>Comments</h2>
    <ul>
        {% for comment in comments %}
            <li><strong>{{ comment.author }}:</strong> {{ comment.content }}</li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock content %}

templates/news_list.html
{% extends 'base.html' %}
    {% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News List</title>
</head>
<body>
    <h1>News List</h1>
    <ul>
        {% for news in news_list %}
            <li><a href="{% url 'main:news_detail' news.pk %}">{{ news.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock content %}

templates/register.html
{% extends 'page_wrapper.html' %}
    {% block page %}


	<!-- jp login wrapper start -->
	<div class="login_section">
		<!-- login_form_wrapper -->
		<div class="login_form_wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-8 offset-md-2">
						<!-- login_wrapper -->
						{{ request.user }}
						<h1>Register TO YOUR <a href="{{ request.user.get_absolute_url }}">ACCOUNT cc</a></h1>
						<div class="login_wrapper">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
									<a href="#" class="btn btn-primary"> <span>Login with Facebook</span>  <i class="fab fa-facebook-f"></i> 
									</a>
								</div>
								<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">	<a href="#" class="btn btn-primary google-plus"> Login  with Google <i class="fab fa-google-plus-g"></i></a>
								</div>
							</div>
							<h2>or</h2>
							{% if messages %}
								{% for message in  messages %}
									<h3	class="text-{{ message.tags }}"> {{ message }} </h3>
								{% endfor %}	
							{% endif %}	

						<form action="" method="post" id="form">  
							{% csrf_token %}
							<div class="formsix-pos">
								<div class="form-group">
									<input type="text" name="username" class="form-control" required id="email2" placeholder="Username*">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="email" name="email"  class="form-control" required id="password2" placeholder="Email">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="password" name="password" class="form-control" required="" id="password2" placeholder="Password *">
								</div>
							</div>
							<div class="formsix-e">
								<div class="form-group">
									<input type="password" name="password_confirm" class="form-control" required="" id="password2" placeholder="Re-enter Password *">
								</div>
							</div>
							<div class="formsix-pos">
								<div class="form-group">
									<input type="text" name="phone" class="form-control" required="" id="email2" placeholder="Phone*">
								</div>
							</div>
							<div class="login_remember_box">
								<label class="control control--checkbox">I agreed to the Terms and Conditions.
									<input type="checkbox">	<span class="control__indicator"></span>
								</label>
							</div>
								<div class="login_btn_wrapper">	<button type="submit" href="#" class="btn btn-primary login_btn"> Register Now </button>
							</div>
						</form>
							<div class="login_message">
								<p>Don’t have an account ? <a href="login.html"> LogIn </a> 
								</p>
							</div>
						</div>
						<p>In case you are using a public/shared computer we recommend that you logout to prevent any un-authorized access to your account</p>
						<!-- /.login_wrapper-->
					</div>
				</div>
			</div>
		</div>
		<!-- /.login_form_wrapper-->
	</div>
	<!-- jp login wrapper end -->
	<!--edu letter wrapper Start-->
	<div class="edu_letter_main_wrapper float_left">
		<div class="container">
			<div class="edu_left_envo">
				<img src="/static/images/innn.png" alt="img">
				<h3>Sign up for Newsletter</h3>
			</div>
			<div class="edu_right_form">
				<input type="text" placeholder="Enter your email">
				<button>Sign Up</button>
			</div>
		</div>
	</div>

    {% endblock  %}